version: "3"
services:
    myapp:
        build: .
        pull_policy: build
        restart: unless-stopped
        ports:
            - "3000:3000"
        environment:
            - PROTECT_ROUTES=${PROTECT_ROUTES}
            - API_KEY=${API_KEY}